site_name: PowerBI Notes # You can change this to anything you like
site_url: https://numanbadr.github.io/power-bi-notes/ # IMPORTANT: Update this line!
repo_url: https://github.com/numanbadr/power-bi-notes/
site_dir: site
use_directory_urls: true
docs_dir: docs
nav:
  - Home: index.md
  - Intro: 
    - PowerBI: intro/intro-to-powerbi.md
    - PL-300: intro/about-pl-300.md
  - PowerBI:
    # - Import Data: 
    #   - File Types: power-bi/import-data/file-types.md
    #   - Import Types: power-bi/import-data/import-types.md
    # - Transform Data: 
      # - Column: power-bi/transform-data/column-based.md
      # - Row: power-bi/transform-data/row-based.md
    - Combine Data:
      - Append Queries: power-bi/combine-data/append.md
      - Merge Queries: power-bi/combine-data/merge.md



theme:
  name: material
  logo: assets/N_Logo.png
  favicon: assets/N_logo_icon.png

  font:
    text: Roboto

  palette: 
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: amber
      scheme: default
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - navigation.tracking

plugins:
  - search
    