extra_css:
  - overrides/custom.css

site_name: PowerBI Notes # You can change this to anything you like
site_url: https://numanbadr.github.io/power-bi-notes/ # IMPORTANT: Update this line!
repo_url: https://github.com/numanbadr/power-bi-notes/
site_dir: site
use_directory_urls: true
docs_dir: docs
nav:
  - Home: 
    - PowerBI: index.md
    # - PL-300: intro/about-pl-300.md
  - Class:
    # - Import Data: 
    #   - File Types: power-bi/import-data/file-types.md
    #   - Import Types: power-bi/import-data/import-types.md
    # - Transform Data: 
      # - Column: power-bi/transform-data/column-based.md
      # - Row: power-bi/transform-data/row-based.md
    - Transformation:
      - Parameter: power-bi/combine-data/parameter.md
    - Combine Data:
      - Append Queries: power-bi/combine-data/append.md
      - Merge Queries: power-bi/combine-data/merge.md
    - Table Normalization:
      - Normalization: power-bi/data-normalization/normalization.md
      - Star Schema: power-bi/data-normalization/star-schema.md


theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/N_Logo.png
  favicon: assets/N_logo_icon.png

  font:
    text: Roboto

  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: amber
        toggle:
            icon: material/weather-sunny
            name: Switch to dark mode

    # Palette toggle for dark mode

      - scheme: slate
        primary: deep orange
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - navigation.tracking

plugins:
  - search

markdown_extensions:
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition # For callouts (info, warning, etc.)
- pymdownx.details
- pymdownx.superfences # Enhanced code blocks
- attr_list # For adding attributes to markdown elements
- md_in_html # Allows Markdown within HTML blocks
- toc:
    permalink: true # Adds a link icon next to headings