site_name: PowerBI Notes # You can change this to anything you like
site_url: https://numanbadr.github.io/power-bi-notes/ # IMPORTANT: Update this line!

nav:
  - Home: index.md
  - My Notes: notes.md # We'll add this file in the next step

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy # Adds a copy button to code blocks
  palette:
    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate # A darker base for the custom colors
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  custom_dir: overrides # This points to a directory for custom CSS/JS

extra:
  social:
    # Example social links (optional)
    - icon: fontawesome/brands/github
      link: https://github.com/numanbadr
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/numanbadr # Replace with your actual LinkedIn
  # Add this to ensure search and other features are enabled
  search:
    pipeline:
      - stemmer
    lang: en # Or other languages if needed

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition # For callouts (info, warning, etc.)
  - pymdownx.details
  - pymdownx.superfences # Enhanced code blocks
  - attr_list # For adding attributes to markdown elements
  - md_in_html # Allows Markdown within HTML blocks
  - toc:
      permalink: true # Adds a link icon next to headings

extra_css:
  - custom.css # We'll create this file

# Required for search functionality
plugins:
  - search